[general]
import = ["vague.toml"]

[window]
startup_mode = "Maximized"
decorations = "None"
dynamic_title = false
dynamic_padding = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 18.0

[cursor]
style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true

